version: "3.8"

volumes:
  datastorage:
services:
 notebook:
   image: "jupyter/datascience-notebook"
   volumes:
     - type: bind
       source: .
       target: "/home/jovyan/work"
   ports:
     - target: 8888
       published: 8888
       protocol: tcp

#-------
 database:
   image: mariadb
   volumes:
     - type: volume
       source: datastorage
       target: /var/lib/mysql
   environment:
     MARIADB_ROOT_PASSWORD: mariadb


